name: chat_app
description: A modern chat application with real-time messaging, voice/video calls, and file sharing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication & Security
  local_auth: ^2.1.6
  crypto: ^3.0.3

  # Real-time Communication
  socket_io_client: ^2.0.3+1

  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0

  # UI Components
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  animations: ^2.0.8
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Permissions & Device Features
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

  # Navigation
  go_router: ^12.1.1

  # Utils
  intl: ^0.18.1
  timeago: ^3.5.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

  # Audio/Video
  agora_rtc_engine: ^6.2.6
  audioplayers: ^5.2.1
  record: ^5.0.4

  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: ChatAppIcons
      fonts:
        - asset: assets/fonts/ChatAppIcons.ttf